//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CashierGUI.rc
//
#define IDS_STRING1                     1
#define IDS_OTP_NOERR                   1
#define IDS_STRING2                     2
#define IDS_OTP_COM_ERR                 2
#define IDC_REFRESH                     3
#define ID_WAIT_OTP_POLL                3
#define IDS_OTP_FILE_OPEN               3
#define ID_SET_TIME_READ_VER            4
#define IDS_OTP_INVPARAM                4
#define IDOK3                           4
#define IDS_OTP_FILE_READ               5
#define IDS_OTP_COM_INVRESP             6
#define IDS_OTP_FILE_CHECKSUM           7
#define IDS_OTP_CSCREAD                 8
#define IDS_OTP_CSCWRITE                9
#define IDS_OTP_CSCBLOCK                10
#define IDS_OTP_NOCSC                   11
#define IDS_OTP_INCOMP                  12
#define IDS_OTP_TLOGFULL                13
#define IDS_OTP_CSCBLOCKED              14
#define IDS_OTP_POLLTIME                15
#define IDS_OTP_POLLAUTH                16
#define IDS_OTP_POLLRECOVER             17
#define IDS_OTP_NOFUND                  18
#define IDS_OTP_EXCLMT                  19
#define IDS_OTP_AVEXPIRE                20
#define IDS_OTP_CTRLID                  21
#define IDS_OTP_WRITEID                 22
#define IDS_OTP_DEFER_NOMORE            23
#define IDS_OTP_DEFER_STATE             24
#define IDS_OTP_FIRM_NONE               25
#define IDS_OTP_FIRM_DONE               26
#define IDS_OTP_OPEN_AR                 27
#define IDS_OTP_OPEN_UD                 28
#define IDS_OTP_CCHS_1005               29
#define IDS_OTP_CCHS_1006               30
#define IDS_OTP_CCHS_1007               31
#define IDS_OTP_CCHS_1008               32
#define IDS_OTP_CCHS_1009               33
#define IDS_OTP_DIFFER_CARD             34
#define IDS_OTP_UNKNOWN                 35
#define IDS_OTP_USAGEEXCEED             36
#define IDD_ABOUTBOX                    100
#define IDD_TRYPCKDEIMP_DIALOG          102
#define ENTERGRACETIME                  111
#define IDR_MAINFRAME                   128
#define IDR_CASHIETYPE                  129
#define IDB_SPLASH                      130
#define IDR_TIME                        131
#define IDR_OPERATOR                    133
#define IDD_LOGIN                       135
#define IDB_KEY                         137
#define IDD_SETTING                     138
#define IDD_SETTING_SYSTEM              139
#define IDD_SETTING_COMMUNICATE         139
#define IDD_SETTING_PERIPHERAL          140
#define IDD_SETTING_RECEIPT             141
#define IDD_MESSAGEBOX                  142
#define IDD_SETTING_OTPREADER           143
#define IDD_DIALOG1                     144
#define IDD_TRYPCREADER_DIALOG          144
#define IDD_PAYMENT_OTP                 145
#define IDD_PAYMENT_CASH                146
#define IDD_PAYMENT_KDE                 147
#define IDB_CARDOTP                     149
#define IDR_STATUS                      150
#define IDR_STATUS1                     151
#define IDR_STATUS2                     152
#define IDD_EVENTLOG                    153
#define IDI_KEY                         154
#define IDD_RATE                        155
#define IDD_RATE_FEE                    156
#define IDD_RATE_TIMEZONE               157
#define IDD_RATE_CARTYPE                158
#define IDD_RATE_GROUP                  159
#define IDD_RATE_DAY                    160
#define IDD_RATE_FIX                    161
#define IDD_PAYMENT                     162
#define IDD_PAYMENT_HAND_KDE_TICKET     170
#define IDB_CARDKDEERROR                177
#define IDB_CARDKDE                     179
#define IDB_CARDOTPERROR                181
#define IDD_PAYMENT_HAND_KDE_ENTRYTIME  182
#define IDD_SPLASH                      183
#define IDD_RATE_CALCULATE              184
#define IDI_CASH                        186
#define IDD_PAYMENT_RECEIPT             187
#define IDD_PAYMENT_HAND_OTP_ENTRYTIME  189
#define IDD_PAYMENT_HAND_ENTRYTIME      189
#define IDD_PAYMENT_OTP_ADDVALUE        190
#define IDD_CARD_CREATE2                191
#define IDD_PAYMENT_OTP_CARD            192
#define IDD_CARD_CATEGROY               193
#define IDB_SETTING                     194
#define IDD_CARD_CREATE4                194
#define IDD_CARD_CREATE1                195
#define IDD_CARD_CREATE3                196
#define IDD_CARD_SEARCH                 198
#define IDD_PAYMENT_KDE_CARD            203
#define IDD_PAYMENT_HAND_OTP_TICKET     206
#define IDD_SETTING_PAYMODE             207
#define IDD_SETTING_DISCOUNTPLAN        209
#define IDD_PAYMENT_SHIFTACCOUNT        210
#define IDD_PAYMENT_RECEIPT_SHIFTACCOUNT 211
#define IDD_PAYMENT_RECEIPT_CLOSEACCOUNT 212
#define IDD_SETTING_CALCULATERULE       215
#define IDD_SETTING_STATION             216
#define IDD_SETTING_CARDTYPE            219
#define IDD_SETTING_GROUPTYPE           220
#define IDD_SETTING_PAYMODETYPE         221
#define IDD_SETTING_CARTYPE             222
#define IDD_TRY_MNT                     223
#define IDD_CARD_CREATE                 225
#define IDD_PAYMENT_PARK_FEE            226
#define IDI_ICON_SLASH                  228
#define IDR_ACCOUNT                     237
#define IDD_PAYMENT_ACCOUNT             239
#define IDD_SETTING_RECEIPT_FORMAT      240
#define IDD_PAYMENT_OTP_PRE_ADDVALUE    241
#define IDD_PAYMENT_OTP_SUB_ADDVALUE    242
#define IDD_SETTING_PERMISSION          244
#define IDD_PROGRESS                    245
#define IDD_RECEIPT_PARKING_FEE         247
#define IDD_VIEW_OTP_CARD               249
#define IDD_SETTING_SYS_PARAMETERS      253
#define IDD_VIEW_KDE_CARD               254
#define IDD_TOOL_KDE                    255
#define IDI_ICON_PARTICULARS            257
#define IDI_ICON_CREATE1                260
#define IDB_PAYMENT_LABEL               260
#define IDI_ICON_CREATE2                261
#define IDD_PAYMENT_SELECT_DISCOUNT     261
#define IDI_ICON_CREATE4                263
#define IDD_CHECKCARD                   265
#define IDD_DLG_CONFEXIT                267
#define IDB_DISCOUNT                    272
#define IDB_CASH                        273
#define IDD_DLG_RENEW                   274
#define IDD_DLG_TOSHIP                  276
#define IDB_CEXIT                       281
#define IDB_SHIP                        283
#define IDB_PROCESS                     289
#define IDB_CHECK                       290
#define IDD_DLG_OTP_RECORD              292
#define IDD_MSGBOX_WAIT                 294
#define IDD_DLG_PAYMODE                 295
#define IDD_PAYMENT_PARK_FEE1           296
#define IDD_PAYMENT_HAND_TICKET         297
#define IDC_LCDPORT                     1000
#define IDC_BUTTON1                     1000
#define IDC_BUTTON001                   1000
#define IDC_TAB_SETTING                 1001
#define IDC_LCDBAUDRATE                 1001
#define IDC_BUTTON2                     1001
#define IDC_BUTTON002                   1001
#define IDC_RADIO1                      1002
#define IDC_BUTTON11                    1002
#define IDC_RECEIPTBAUDRATE             1002
#define IDC_RADIO_SPECIAL               1002
#define IDC_RADIO_OTP                   1002
#define IDC_RADIO_CE_OTP                1002
#define IDC_RADIO2                      1003
#define IDC_RADIO_HOURLY                1003
#define IDC_RADIO_KDE                   1003
#define IDC_RADIO_CE_KDE                1003
#define IDC_RADIO3                      1004
#define IDC_LABEL_0                     1004
#define ID_AV100                        1004
#define IDC_RADIO_CE_OCTOPUS            1004
#define IDC_RADIO_DAMG                  1004
#define IDC_OTPREADERPORT               1005
#define IDC_RADIO4                      1005
#define IDC_LABEL_1                     1005
#define IDC_COMBO_TYPE                  1005
#define IDC_OTP_PORT                    1005
#define IDC_RADIO_CE_NORMALTK           1005
#define IDC_RADIO_LOST                  1005
#define IDC_OTPREADERBAUDRATE           1006
#define IDC_RADIO5                      1006
#define IDC_LABEL_2                     1006
#define IDC_OTP_BAUD_RATE               1006
#define ID_AV200                        1006
#define IDC_RADIO_CE_DAMGTK             1006
#define IDC_RADIO_FR_SEA                1006
#define IDC_DEFAULTSYSTEMPRINTER        1007
#define IDC_CHECK_Red                   1007
#define IDC_LABEL_3                     1007
#define IDC_EDIT_REDEMPT                1007
#define IDC_KDE_PORT                    1007
#define IDC_CASHIERSTATIONSENDSOCKETPORT 1008
#define IDC_KDEREADERPORT               1008
#define IDC_CHECK_Green                 1008
#define IDC_LABEL_4                     1008
#define IDC_EDIT_REMARK                 1008
#define IDC_PRINTER_PORT                1008
#define IDC_SEND_PORT                   1008
#define ID_AV300                        1008
#define IDC_CARPARKMANAGEMENTADDRESSID  1009
#define IDC_KDEREADERBAUDRATE           1009
#define IDC_AMT_LINE1                   1009
#define IDC_LABEL_5                     1009
#define IDC_EDIT_VEHTYPE                1009
#define IDC_KDE_BAUD_RATE               1009
#define IDC_MNT_ID                      1009
#define IDC_AMT_LINE2                   1010
#define IDC_LABEL_6                     1010
#define IDC_EDIT_STN                    1010
#define IDC_LCD_BAUD_RATE               1010
#define ID_AV400                        1010
#define IDC_CARPARKMANAGEMENTIP         1011
#define IDC_BUTTON3                     1011
#define IDC_LABEL_7                     1011
#define IDC_EDIT_ENTERTIME              1011
#define IDC_LCD_PORT                    1011
#define IDC_MNT_IP                      1011
#define IDC_BUTTON4                     1012
#define IDC_LABEL_8                     1012
#define IDC_EDIT_PAYSTN                 1012
#define IDC_PRINTER_BAUD_RATE           1012
#define IDC_STATION_IP                  1012
#define ID_AV500                        1012
#define IDC_PRINTERFORRECEIPT           1013
#define IDC_BUTTON5                     1013
#define IDC_LABEL_9                     1013
#define IDC_RECEIPTPORT                 1013
#define IDC_EDIT_PAYTIME                1013
#define IDC_OPERATORNAME                1014
#define IDC_BUTTON6                     1014
#define IDC_LABEL_10                    1014
#define IDC_EDIT_PAYNUM                 1014
#define IDC_PASSWORD                    1015
#define IDC_BUTTON7                     1015
#define IDC_LABEL_11                    1015
#define IDC_EDIT_PAYAMT                 1015
#define IDC_BUTTON8                     1016
#define IDC_LABEL_12                    1016
#define IDC_BUTTON003                   1016
#define IDC_CASHIERSTATIONNAME          1017
#define IDC_BUTTON9                     1017
#define IDC_TICKET_NO                   1017
#define IDC_BUTTON004                   1017
#define IDC_LABEL_13                    1017
#define IDC_STATION_NAME                1017
#define IDC_CASHIERSTATIONID            1018
#define IDC_EDIT_NEWXFILE               1018
#define IDC_ENTRY_DATE                  1018
#define IDC_BUTTON005                   1018
#define IDC_LABEL_14                    1018
#define IDC_STATION_ID                  1018
#define IDC_CASHIERSTATIONADDRESSID     1019
#define IDC_ENTRY_TIME                  1019
#define IDC_BUTTON006                   1019
#define IDC_PAY_CARD_NO                 1019
#define IDC_CASHIERSTATIONRECEIVESOCKETPORT 1020
#define IDC_EDIT5                       1020
#define IDC_PAY_DATE                    1020
#define IDC_EDIT11                      1020
#define IDC_RECV_PORT                   1020
#define IDC_CARD_CATEGORY               1020
#define NEWTRANSTIMES                   1020
#define IDC_EDIT_CAN                    1021
#define IDC_PAY_TIME                    1021
#define IDC_EVENTLOG_KEY                1021
#define IDC_LEFTBLACKSPACES             1021
#define IDC_EDIT_HOLDER                 1021
#define IDC_EDIT_AVDETAIL               1022
#define IDC_DURATION                    1022
#define IDC_LINESPACES                  1022
#define IDC_EDIT12                      1022
#define IDC_PAID                        1022
#define IDC_EDIT_REGTIME                1022
#define IDC_EDIT_AVMACH                 1023
#define IDC_PAY_RULE                    1023
#define IDC_EDIT13                      1023
#define IDC_REMAIN                      1023
#define IDC_STATIC_MESSAGE              1024
#define IDC_EDIT_CLASS                  1024
#define IDC_PARKING_FEE                 1024
#define IDC_EDIT14                      1024
#define IDC_CARD_REMAIN                 1024
#define IDC_ADD_VALUE_DETAIL            1024
#define IDC_EDIT_LANG                   1025
#define IDC_DISCOUNT_RULE               1025
#define IDC_EDIT16                      1025
#define IDC_STORE_VALUE                 1025
#define IDC_LAST_ADD_VALUE_DEVICE       1025
#define IDC_EDIT_APS                    1026
#define IDC_DISCOUNT                    1026
#define IDC_BUTTON007                   1026
#define IDC_CLASS                       1026
#define IDC_EDIT_DDAMT                  1027
#define IDC_AMOUNT                      1027
#define IDC_BUTTON008                   1027
#define IDC_LANGUAGE                    1027
#define IDC_EDIT_DDRMT                  1028
#define IDC_RECEIVE                     1028
#define IDC_AVAILABLE_AMOUNT            1028
#define IDC_EDIT_AVAMT                  1029
#define IDC_CHANGE                      1029
#define IDC_BUTTON0010                  1029
#define IDC_MANUFACTURE_ID              1029
#define IDC_EDIT_AVRMT                  1030
#define IDC_LIST_MAIN                   1030
#define IDC_EDIT1                       1030
#define REMAIN                          1030
#define IDC_CHECK_NEGVAL                1031
#define IDC_Accept                      1031
#define MODECASHBACK                    1031
#define IDC_EDIT_HOUSEKEP_TYPE          1032
#define IDC_TAB_RATE                    1032
#define MODESTROEVALUE                  1032
#define PAIDGRACETIME                   1032
#define IDC_EDIT_PORTNUM                1033
#define TZONEGRACETIME                  1033
#define IDC_EDIT_BAUDRATE               1034
#define IDC_LIST                        1034
#define LOSTTICKETPENALTY               1034
#define IDC_EDIT_TIMEOUT                1035
#define IDC_BUTTON_REFRASH              1035
#define IDC_EDIT_XFILEPATH              1036
#define IDC_STATIC1                     1036
#define CREDITLIMIT                     1036
#define IDC_OPERATORACTIONLOG           1036
#define IDC_BUTTON_BACK                 1036
#define IDC_EDIT_BLISTPATH              1037
#define IDC_DLGEVENTLOG_DATE_BEGIN      1037
#define IDC_TITLE1                      1037
#define PERENTRYAMT                     1037
#define IDC_PAYMENT                     1037
#define IDC_EDIT_FWAREPATH              1038
#define IDC_EVENTLOG_LIST               1038
#define IDC_TITLE2                      1038
#define IDC_EDIT_EODPATH                1039
#define IDC_DLGEVENTLOG_DATE_END        1039
#define IDC_TITLE3                      1039
#define IDC_EDIT_CCHSPATH               1040
#define IDSEARCH                        1040
#define IDC_ENDING1                     1040
#define IDC_EDIT_ARPATH1                1041
#define IDC_EVENTLOG_TYPE               1041
#define IDC_ENDING2                     1041
#define IDC_EDIT_ARPATH2                1042
#define IDPRINT                         1042
#define IDC_FEEDLINES                   1042
#define IDC_EDIT_DAYKEEP                1043
#define IDC_TAXNAME                     1043
#define IDC_RECEIPT                     1043
#define IDC_TAXREGNO                    1044
#define IDC_EDIT_DEVID                  1045
#define IDC_TAXPECENTAGERATE            1045
#define IDC_EDIT_OPTRID                 1046
#define IDC_TICKETNO                    1046
#define IDC_EDIT_COMPID                 1047
#define IDC_EDIT_LOCID                  1048
#define IDC_EDIT_DEVTIME                1049
#define IDC_TEXT_RESULT                 1049
#define IDC_EDIT_BLIST                  1050
#define IDC_ENTRYDATE                   1050
#define IDC_EDIT_EOD                    1051
#define IDC_ENTRYTIME                   1051
#define IDC_CURRENT_OPR                 1051
#define IDC_EDIT_FWARe                  1052
#define IDC_EXITDATE                    1052
#define IDC_EDIT_CCHS                   1053
#define IDC_EXITTIME                    1053
#define IDC_EDIT_KEY                    1054
#define IDC_BUTTON10                    1055
#define IDC_VEHICLE_TYPE                1055
#define IDC_EDIT_NEWLOCID               1056
#define IDC_DETAILS                     1056
#define IDC_EDIT_RMT                    1057
#define IDC_PROGRESS1                   1057
#define IDC_CARD_NUMBER_PART            1057
#define IDC_EDIT_ERRCODE                1058
#define IDC_END1                        1058
#define IDC_EDIT_TIME                   1059
#define IDC_END2                        1059
#define IDC_EDIT_RMT2                   1060
#define IDC_TAX_NAME                    1060
#define IDC_EDIT_MID                    1061
#define IDC_TAX_REG_NO                  1061
#define IDC_TAX_PECENTAGE_RATE          1062
#define IDC_ERROR_KDE_CARD              1063
#define IDC_ERROR_OTP_CARD              1064
#define IDC_OTP_CARD_ADD_VALUE          1065
#define CUR_STATUS                      1066
#define IDC_SHIFT_ACCOUNT               1066
#define AMOUNT                          1067
#define CUR_STATUS3                     1067
#define RECEIVE                         1068
#define CUR_STATUS4                     1068
#define CHANGE                          1069
#define CUR_STATUS2                     1070
#define STOREVALUE_REMAIN               1070
#define OCTOPUS_REMAIN                  1071
#define OCTOPUS_CARDNO                  1072
#define UNPAID                          1073
#define IDC_CATEGORY                    1074
#define IDC_CARD_TYPE                   1075
#define IDC_CARD_NO                     1076
#define IDC_DESCRIPTION                 1077
#define IDC_SEARCH                      1078
#define IDC_ENTRY_STATION               1078
#define ID_CHANGE_MODE                  1079
#define ID_PAY                          1080
#define IDC_PAY_STATION                 1080
#define IDC_PAYMENT_TIMES               1083
#define IDC_TIMESYNCHRONIZE             1085
#define IDC_REMARK                      1085
#define IDC_CLOSEACCOUNT                1086
#define IDC_NONPARKINGPAYMENT           1086
#define IDC_FINANCIALMAINTAIN           1087
#define IDC_SHIP                        1087
#define IDC_ERRORWARNNOTICELOG          1088
#define PAYMENT_LIST                    1092
#define ACCOUNT_LIST                    1093
#define MODECASHCARD                    1095
#define IDC_CALCULATE                   1096
#define IDC_CHECK1                      1097
#define IDC_CHANGELISTWIDTH             1097
#define IDC_CHECK2                      1098
#define WITHDRAWAL                      1098
#define IDC_CHECK3                      1099
#define CONFIRM                         1099
#define CURBALANCE                      1100
#define BALANCE                         1101
#define IDC_TITLE                       1102
#define IDC_OPERATER                    1103
#define IDC_WITHDRAWAL                  1104
#define IDC_OLDBALANCE                  1105
#define IDC_BALANCE                     1106
#define IDC_TIME                        1107
#define IDC_DATE                        1108
#define IDC_LOGINTIME                   1109
#define IDC_LOGOUTTIME                  1110
#define IDC_VEHICLETYPE                 1114
#define IDC_GROUPID                     1115
#define IDC_RECEIPTNO                   1116
#define IDC_CARD_TYPE_PART              1116
#define IDC_PERIOD                      1117
#define PERIOD_AMOUNT                   1117
#define IDC_TRANSACTION                 1118
#define TRANSACTION_AMOUNT              1118
#define IDC_STOREVALUE                  1119
#define STORE_VALUE                     1119
#define IDC_JOININGFEE                  1120
#define JOINING_FEE                     1120
#define IDC_CARDFEE                     1121
#define CARD_FEE                        1121
#define IDC_TOTAL                       1122
#define TOTAL                           1122
#define IDC_BUTTON_NEXT                 1123
#define PRINT_RECEIPT                   1125
#define CASH                            1126
#define OCTOPUS                         1127
#define IDC_BIG_O                       1130
#define IDC_ENTRYSTATION                1132
#define RECEIPTNO                       1133
#define IDC_GROUPTYPE                   1134
#define AMOUNT_REMAIN                   1135
#define CASH_REMAIN                     1136
#define OPERATER                        1137
#define CASHKEEP_REMAIN                 1137
#define OLDBALANCE                      1138
#define OCTUPOS                         1139
#define DATE                            1140
#define TIME                            1141
#define IDC_BIG_P                       1142
#define AMOUNT_TOTAL                    1143
#define IDC_EDIT_NAME                   1144
#define IDC_NAME                        1144
#define CASH_TOTAL                      1144
#define IDC_EDIT_IC                     1145
#define IDC_IC                          1145
#define OCTOPUS_TOTAL                   1145
#define STOREVALUE_TOTAL                1146
#define IDC_EDIT_TEL                    1147
#define IDC_TEL                         1147
#define IDC_UPLOADOTPXFILE              1148
#define IDC_OTP_STEP                    1153
#define IDC_BTN_SEARCH                  1154
#define IDC_QUERY                       1154
#define IDC_KDE_STEP                    1155
#define IDC_LCD_STEP                    1156
#define IDC_PRINTER_STEP                1157
#define IDC_SEND_THREAD_STEP            1158
#define IDC_PROGRESS                    1159
#define IDC_OPERATE                     1161
#define IDC_ELAPSE                      1162
#define IDC_RECEIPT_NO                  1163
#define IDC_TAX_PECENTAGE               1164
#define IDC_ENTRY                       1165
#define IDC_TIME_ENTRY                  1165
#define IDC_TIME_PAY                    1167
#define IDC_OTP_CARDNO                  1168
#define IDC_STOREVALUE_CARDNO           1169
#define IDC_COMPID                      1170
#define IDC_DEVID                       1171
#define IDC_OPERID                      1172
#define IDC_EDIT_ID                     1173
#define IDC_ID                          1173
#define IDC_DEVTIME                     1173
#define IDC_KEYVER                      1174
#define IDC_EODVER                      1175
#define IDC_EDIT_PLATE                  1176
#define IDC_PLATE                       1176
#define IDC_BLVER                       1176
#define IDC_FIRMVER                     1177
#define IDC_EDIT_ADDR1                  1178
#define IDC_ADDR1                       1178
#define IDC_CCHSVER                     1178
#define IDC_EDIT_ADDR2                  1179
#define IDC_ADDR2                       1179
#define IDC_EDIT_ADDR3                  1180
#define IDC_ADDR3                       1180
#define IDC_MSG_LIST                    1180
#define IDC_EDIT_ZIP                    1181
#define IDC_ZIP                         1181
#define IDC_LOCID                       1181
#define IDC_STATIC_PORTRAIT             1182
#define IDC_BLISTPATH                   1182
#define IDC_FWAREPATH                   1183
#define IDC_EODPATH                     1184
#define IDC_CCHSPATH                    1185
#define IDC_XFILEPATH                   1186
#define IDC_ARPATH1                     1187
#define IDC_ARPATH2                     1188
#define ID_SET_FOLDERS                  1189
#define ID_READ_FOLDERS                 1190
#define ID_READ_TICKET                  1190
#define IDC_STATIC2                     1191
#define IDC_STATIC3                     1192
#define IDC_STATIC4                     1193
#define IDC_BTN_DETAILS                 1194
#define IDC_AUTOGAINNO                  1194
#define IDC_STATIC5                     1194
#define IDC_STATIC6                     1195
#define IDC_STATIC7                     1196
#define IDC_DATE_FROM                   1198
#define PERIODFROM                      1198
#define IDC_STATIC_TITLE                1198
#define IDC_DATE_TO                     1199
#define PERIODTO                        1199
#define IDC_EDIT2                       1199
#define IDC_STATIC_TITLE2               1199
#define IDC_RADIO_1M                    1200
#define RADIO_1M                        1200
#define IDC_EDIT3                       1200
#define IDC_RADIO_6M                    1201
#define RADIO_6M                        1201
#define IDC_EDIT_TOTALAMT               1201
#define IDC_EDIT_VALIDITY               1201
#define IDC_RADIO_2M                    1202
#define RADIO_2M                        1202
#define IDC_EDIT_CASHAMT                1202
#define IDC_RADIO_1Y                    1203
#define RADIO_12M                       1203
#define IDC_EDIT_OTPAMT                 1203
#define IDC_RADIO_3M                    1204
#define RADIO_3M                        1204
#define IDC_EDIT_SVAMT                  1204
#define IDC_RADIO_2Y                    1205
#define RADIO_24M                       1205
#define IDC_EDIT_CUROPTR                1205
#define IDC_EDIT_DUTYSTART              1206
#define IDC_LIST1                       1207
#define IDC_EDIT_ENTSTN                 1208
#define IDC_EDIT_CATE_BRIEF             1209
#define IDC_EDIT_TRANSADD               1209
#define IDC_CATE_BRIEF                  1209
#define TRANSTIMES                      1209
#define IDC_TYPE_BRIEF                  1209
#define IDC_EDIT_EXTSTN                 1209
#define IDC_EDIT_TRANSNEW               1210
#define IDC_EDIT_FEE_PERIOD             1211
#define IDC_EDIT_CASHMAINTAIN           1211
#define IDC_EDIT_VEHNO                  1212
#define IDC_EDIT_CASHKEEP               1212
#define IDC_EDIT_SVORG                  1214
#define IDC_EDIT_FEE_TRANS              1214
#define IDC_EDIT_CARDNO                 1214
#define IDC_EDIT_SVNEW                  1215
#define IDC_EDIT_FEE_SVALUE             1215
#define IDC_EDIT_CATE                   1215
#define IDC_EDIT_FEE_CARD               1216
#define IDC_EDIT_ENTTIME                1216
#define IDC_STATICX                     1217
#define IDC_EDIT_EXTTIME                1217
#define IDC_COMBO1                      1218
#define IDC_EDIT_KIND                   1218
#define IDC_EDIT_SVADD                  1219
#define STOREVALUE                      1219
#define IDC_EDIT_CREDIT                 1219
#define IDC_EDIT_TRANSORG               1220
#define ADAMT                           1220
#define IDC_STATIC_WMODE                1220
#define ADDSTOREVALUE                   1220
#define ADNUM                           1221
#define ID_AV50                         1221
#define NEWSTOREVALUE                   1221
#define SCMGNAMT                        1222
#define ID_AVSEL                        1222
#define STOREVALUE_AMOUNT               1222
#define SCMGNNUM                        1223
#define IDC_RADIO_CATE1                 1224
#define IDC_CATE1                       1224
#define IDC_RADIO_CATE2                 1225
#define IDC_CATE2                       1225
#define IDC_SEL_DISCOUNT                1225
#define IDC_RADIO_CATE3                 1226
#define IDC_CATE3                       1226
#define IDC_RADIO_CATE4                 1227
#define IDC_CATE4                       1227
#define ID_DISCOUNT_LIST                1227
#define IDC_RADIO_CATE5                 1228
#define IDC_STATIC_PERIOD               1229
#define PERIOD                          1229
#define IDC_EDIT_FEE_JOIN               1230
#define IDC_EDIT_FEE_TOTAL              1231
#define ADDTRANSTIMES                   1231
#define IDC_BTN_SET                     1232
#define IDC_CARDTYPE                    1232
#define IDC_RADIO_NEW                   1233
#define RADIO_NEW                       1233
#define IDC_CARDNUM                     1233
#define IDC_RADIO_EXIST                 1234
#define RADIO_EXIST                     1234
#define IDC_ORGPERIOD                   1234
#define IDC_EDIT_PORTRAIT               1235
#define IDC_CURPERIOD                   1235
#define IDC_BTN_PORTRAIT                1236
#define ORGTRANSTIMES                   1236
#define ORGSTOREVALUE                   1237
#define IDC_STATIC_1                    1238
#define IDC_RADIO_NO                    1239
#define RADIO_NO                        1239
#define IDC_STATIC_2                    1239
#define IDC_STATIC_PERIOD_PRICE         1240
#define PERIOD_PRICE                    1240
#define IDC_STATIC_TRANS                1241
#define TRANSACTION                     1241
#define IDC_STATIC_3                    1241
#define IDC_STATIC_TRANS_PRICE          1242
#define TRANSACTION_PRICE               1242
#define IDC_STATIC_4                    1243
#define IDC_STATIC_5                    1244
#define IDC_STATIC_6                    1245
#define IDC_STATIC_ENABLEOTP            1246
#define IDC_MSG_LIST2                   1247
#define IDC_DATETIMEPICKER1             1248
#define IDC_DATETIMEPICKER2             1249
#define IDC_EDIT_PAYMENTTIME            1252
#define IDC_EDIT_PAYMENTSTN             1253
#define IDC_DATEPICKER_TOSHIP           1257
#define IDC_TIMEPICKER_TOSHIP           1258
#define IDC_EDIT_SHIFT_TOTALAMT         1260
#define IDC_EDIT_SHIFT_OTPAMT           1261
#define SHIFT_CASHMAINTAIN              1262
#define IDC_CHECK_DUPLICATE             1263
#define IDC_RADIO_CE_LOSTTK             1263
#define IDC_EDIT_SHIFT_CASHAMT          1264
#define IDC_RADIO_CHANGE_VT             1264
#define IDC_EDIT_SHIFT_SVAMT            1265
#define IDC_EDIT_REMARKS                1268
#define IDC_CHANGE_VEHTYPE              1269
#define IDC_LAST4RECORD                 1272
#define IDC_LIST2                       1273
#define IDC_CARDNO                      1274
#define IDC_BTN_OTP                     1275
#define CARDNO                          1276
#define IDC_EDIT_ENTRYSTATION           1279
#define IDC_IMAGE_OTP                   1280
#define IDC_STATIC11                    1282
#define IDC_TAB1                        1283
#define IDC_SPIN1                       1296
#define IDC_EDIT_DUP_NUM                1389
#define IDC_EDIT_DUPNUM                 1390
#define ID_CURRENT_TIME                 32771
#define ID_BUTTON32772                  32772
#define ID_VIEW_OPERATOR_BAR            32773
#define ID_VIEW_TIME_BAR                32774
#define ID_SETTING_SYSTEM               32775
#define ID_SETTING_TRYOTPREADER         32776
#define ID_BUTTON32777                  32777
#define ID_BUTTON32778                  32778
#define ID_BUTTON32779                  32779
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define ID_STATUS_OTP_ERROR             32782
#define ID_BUTTON32783                  32783
#define ID_BUTTON32784                  32784
#define ID_BUTTON32785                  32785
#define ID_STATUS_MNT_STOP              32789
#define ID_STATUS_MNT_NORMAL            32790
#define ID_STATUS_MNT_ERROR             32791
#define ID_STATUS_OTP_STOP              32792
#define ID_STATUS_OTP_NORMAL            32793
#define ID_STATUS_KDE_STOP              32794
#define ID_STATUS_KDE_NORMAL            32795
#define ID_STATUS_KDE_ERROR             32796
#define ID_EVENT_LOG                    32808
#define ID_CALCULATE                    32810
#define ID_SETTING_FEERATE              32816
#define ID_SP_SEARCH                    32817
#define ID_CARD_SEARCH                  32817
#define ID_SP_TOPUP                     32818
#define ID_CARD_TOPUP                   32818
#define ID_SP_REPLACE                   32819
#define ID_CARD_REPLACE                 32819
#define ID_SP_CREATE                    32820
#define ID_CARD_CREATE                  32820
#define ID_SP_ACTIVATE                  32821
#define ID_CARD_ACTIVATE                32821
#define ID_SETTING_TRYKDEREADER         32822
#define ID_SETTING_CARDCATEGORY         32823
#define ID_SETTING_PAYMODE              32824
#define ID_SETTING_DISCOUNTPLAN         32825
#define ID_SETTING_CALCULATERULE        32826
#define ID_SETTING_STATION              32827
#define ID_MNT_SET_START                32828
#define ID_MNT_SET_STOP                 32829
#define ID_KDE_SET_START                32830
#define ID_KDE_SET_STOP                 32831
#define ID_OTP_SET_START                32832
#define ID_OTP_SET_STOP                 32833
#define ID_SETTING_CARDTYPE             32835
#define ID_SETTING_GROUPTYPE            32836
#define ID_SETTING_PAYMODETYPE          32837
#define ID_SETTING_CARTYPE              32842
#define ID_TRY_MNT                      32843
#define ID_STATUS_MNT_BUSY              32846
#define ID_STATUS_OTP_BUSY              32847
#define ID_STATUS_KDE_BUSY              32848
#define ID_BUTTON32849                  32849
#define ID_VIEW_ACCOUNT_BAR             32850
#define ID_VIEW_ACCOUNT                 32851
#define ID_SETTING_RECEIPT_FORMAT       32852
#define ID_SETTING_PERMISSION           32853
#define ID_TOOL_VIEW_OTP_CARD           32854
#define ID_SETTING_OTP_READER           32855
#define ID_SETTING_SYS_PARAMETERS       32856
#define ID_TOOL_VIEW_KDE_CARD           32857
#define ID_MENUITEM32861                32861
#define ID_OTP_RECORD                   32862
#define KDE_MSG_READCARDERR             61204
#define KDE_MSG_CAPTION                 61205
#define KDE_MSG_READENTERTIMEERR        61206
#define MSG_CONNECT_MNT_ERR             61207
#define SYS_SHOW_DATE                   61208
#define SYS_SHOW_HHMMSS                 61209
#define SYS_SHOW_TIMESPAN               61210
#define SYS_DATETIME_FORMAT             61211
#define SYS_SHOW_DATETIME               61211
#define SYS_STORE_DATE                  61212
#define SYS_SHOW_WEEK11                 61212
#define SYS_STORE_HHMM                  61213
#define SYS_STORE_WEEK                  61214
#define SYS_SHOW_WEEK                   61215
#define SYS_STORE_DATE11                61215
#define SYS_SHOW_HHMM                   61216
#define SYS_SHOW_MONEY                  61217
#define OTP_MSG_CAPTION                 61218
#define OTP_MSG_READENTERTIMEERR        61219
#define ERR_MSG_OPENDATABASE            61220
#define SYS_MSG_CANCEL_PAYMENT          61221
#define SYS_MSG_NOT_ENOUGH              61222
#define SYS_MSG_WARNING                 61223
#define SYS_MSG_CANCEL_OPERATE          61224
#define ERR_READ_KDE_TICKET             61225
#define SYS_MSG_KDE_DEVICE              61226
#define SYS_MSG_MNT_COMMUNICATE         61227
#define SYS_MSG_OTP_DEVICE              61228
#define MNT_ERR_READ_CARD_STATUS        61229
#define MNT_ERR_READ_OPERATOR_MSG       61230
#define MNT_ERR_READ_ENTRYLOG           61231
#define SYS_STORE_DATETIME              61232
#define SYS_SHOW_PERCENTAGE             61233
#define CONFIRM_KDE_START               61234
#define CONFIRM_MNT_START               61235
#define CONFIRM_OTP_START               61236
#define TIP_CARDNO_NUMERIC              61237
#define TIP_CARDNO_LENGTH               61239
#define Err_Read_Entry_Msg              61240
#define Err_No_Entry_Info               61241
#define CONFIRM_MNT_STOP                61242
#define CONFIRM_KDE_STOP                61243
#define CONFIRM_OTP_STOP                61244
#define SPECIAL_CARD_MODE_PERIOD        61245
#define SPECIAL_CARD_MODE_TIMES         61246
#define SPECIAL_CARD_MODE_FREE          61247
#define SPECIAL_CARD_MODE_ILLEGAL       61248
#define TIP_CARD_CATEGORY_ABSENCE       61249
#define TIP_EMPTY_CARDNO                61250
#define TIP_EXIST_CARDNO                61251
#define TIP_ERROR_QUERY                 61252
#define TIP_INVALID_PERIOD              61253
#define TIP_EMPTY_HOLDERID              61254
#define TIP_INEXISTENCE_HOLDERID        61255
#define TIP_DUPLICATE_HOLDERID          61256
#define TIP_EMPTY_NAME_PWD              61257
#define TIP_COMM_ERROR                  61258
#define TIP_INVALID_NAME_PWD            61259
#define TIP_INVALID_ADD_VALUE           61260
#define TIP_MIN_LIMIT_ADD_VALUE         61261
#define TIP_MAX_LIMIT_ADD_VALUE         61262
#define TIP_SUCCESSFUL_ADDVALUE         61263
#define TIP_SHORTAGE_STORE_VALUE        61264
#define TIP_SHORTAGE_OCTOPUS_REMAIN     61265
#define TIP_SHORTAGE_PAYMENT            61266
#define TIP_SUCCESSFUL_OTP_DEDUCT       61267
#define TIP_SUCCESSFUL_SAVE_SETTING     61268
#define TIP_NEGATIVE_CASHREMAIN         61269
#define TIP_NEGATIVE_OCTOPUSREMAIN      61270
#define TIP_NEGATIVE_STOREVALUEREMAIN   61271
#define TIP_KDE_STOP                    61272
#define TIP_KDE_NO_TICKET               61273
#define TIP_KDE_EMPTY_TICKET            61274
#define TIP_INVALID_IO_TIME             61275
#define TIP_NEED_READ_OTP_CARD          61276
#define TIP_OTP_NO_CARD                 61277
#define TIP_NEED_DISCOUNT               61278
#define IDS_STRING_COMM                 61279
#define IDS_STRING_DAYRULE              61280
#define IDS_STRING_GROUPRULE            61281
#define IDS_STRING_VEHRULE              61282
#define IDS_STRING_TZRULE               61283
#define IDS_STRING_FEERULE              61284
#define IDS_STRING_FIXRULE              61285
#define IDS_STRING_CALCULATE            61286
#define IDS_STRING_PERIP                61287
#define IDS_STRING_TIME                 61288
#define IDS_STRING_TYPE                 61289
#define IDS_STRING_MSG                  61290
#define IDS_STRING_CARDNO               61291
#define IDS_STRING_CATEGORY             61292
#define IDS_STRING_VEHTYPE              61293
#define IDS_STRING_STNID                61294
#define IDS_STRING_PAYTIME              61295
#define IDS_STRING_RECEIPTNO            61296
#define IDS_STRING_AMOUNT               61297
#define IDS_STRING_TRANSNO              61298
#define IDS_STRING_DESCRIP              61299
#define IDS_STRING_OPTR                 61300
#define IDS_STRING_CUROPTR              61301
#define IDS_STRING_INDEX                61302
#define IDS_STRING_NAME                 61303
#define IDS_STRING_DISCOUNT             61304
#define IDS_STRING_RULEID               61305
#define IDS_STRING_DATEWEEK             61306
#define IDS_STRING_GROUPID              61307
#define IDS_STRING_TIMEUNIT             61308
#define IDS_STRING_CHARGE               61309
#define IDS_STRING_INZONESTART          61310
#define IDS_STRING_INZONEEND            61311
#define IDS_STRING_INZONEDATE           61312
#define IDS_STRING_OUTZONESTART         61313
#define IDS_STRING_OUTZONEEND           61314
#define IDS_STRING_OUTZONEDATE          61315
#define IDS_STRING_IODAYDIFF            61316
#define IDS_STRING_START                61317
#define IDS_STRING_END                  61318
#define IDS_STRING_UNITRULEID           61319
#define IDS_STRING_WORKMODE             61320
#define IDS_STRING_JOINFEE              61321
#define IDS_STRING_CARDFEE              61322
#define IDS_STRING_UNITPRICE            61323
#define IDS_STRING_WARNLVL              61324
#define IDS_STRING_ISSV                 61325
#define IDS_STRING_PLOTS                61326
#define IDS_STRING_PAYMODE              61327
#define IDS_STRING_NEEDCHANGE           61328
#define IDS_STRING_STNTYPE              61329
#define IDS_STRING_GUEST                61330
#define IDS_STRING_OPTRLVL              61331
#define IDS_STRING_SUPR                 61332
#define IDS_STRING_MGR                  61333
#define IDS_STRING_ADMIN                61334
#define IDS_STRING_SETTING              61335
#define IDS_STRING_IPADDR               61336
#define IDS_STRING_SPID                 61337
#define IDS_STRING_MID                  61338
#define IDS_STRING_AMOUNT2              61339
#define IDS_STRING_AMOUNT3              61340
#define IDS_STRING_AMOUNT1              61341
#define IDS_STRING_PAYMODE2             61342
#define IDS_STRING_PAYMODE3             61343
#define IDS_STRING_PAYMODE1             61344
#define IDS_STRING61345                 61345
#define IDS_CMS_DOWNLOAD                61349
#define IDS_CMS_UPLOAD                  61350
#define IDS_BACKUP                      61351
#define IDS_LOG                         61352
#define IDS_MYCOMPUTER                  61353
#define IDS_MSG_TYPE_ALL                61354
#define IDS_MSG_TYPE_WARNING            61355
#define IDS_MSG_TYPE_ERROR              61356
#define IDS_MSG_TYPE_OPERATOR           61357
#define IDS_MSG_TYPE_SHOWONLY           61358
#define IDS_MSG_TYPE_SYSTEM             61359
#define IDS_MSG_TYPE_DETAIL             61360
#define IDS_STRING_EXITSYS              61361

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        300
#define _APS_NEXT_COMMAND_VALUE         32863
#define _APS_NEXT_CONTROL_VALUE         1284
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
